#!/bin/bash

if [[ $1 == "record" ]]; then
  rr record mrdb $2
elif [[ $1 == "replay" ]]; then
  rr replay -x mruby-rr.gdb
else
  echo "mruby-rr: mruby Time Travaling Recording Debugger"
  echo "Usage:"
  echo "$0 --help : show this help message"
  echo "$0 record rbfile : record the execution of the ruby program"
  echo "$0 replay : replay the execution"
fi
